### ISSUE TITLE
More output on Jasmine tests

### ISSUE THREAD

**Issue by IngwiePhoenix** [thelgevold/javascript-es6-unit-tests#1]
I just used your example repo here to set up my testing environment. I am really pleased with how it worked out, and it was easier than I had thought, ever. 

However, the output is really sparse, I don't even see the names of my tests or anything:

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ npm run test:browser

> BIRD3@3.0.0-dev.76 test:browser /Users/Ingwie/Work/BIRD3
> karma start ./test/browser/karma.conf.js

Clean webpack did not delete path: /Users/Ingwie/Work/BIRD3/cdn/app
Hash: a599e9b987fe8d07b7f6
Version: webpack 1.12.9
Time: 18ms
         Asset     Size  Chunks             Chunk Names
          main  3.54 kB    0, 1  [emitted]  main
test-runner.js  3.54 kB    1, 0  [emitted]  test-runner.js
chunk    {0} main (main) 628 bytes [rendered]
    [0] ./test/browser/test-runner.js 331 bytes {0} {1} [built]
    [1] ./test/browser/tests .+\.test\.(php|oj|js)$ 179 bytes {0} {1} [built]
    [2] ./test/browser/tests/calc.test.js 118 bytes {0} {1} [optional] [built]
chunk    {1} test-runner.js (test-runner.js) 628 bytes [rendered]
    [0] ./test/browser/test-runner.js 331 bytes {0} {1} [built]
    [1] ./test/browser/tests .+\.test\.(php|oj|js)$ 179 bytes {0} {1} [built]
    [2] ./test/browser/tests/calc.test.js 118 bytes {0} {1} [optional] [built]
webpack: bundle is now VALID.
23 12 2015 12:37:13.212:WARN [karma]: No captured browser, open http://localhost:9876/
23 12 2015 12:37:13.217:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
23 12 2015 12:37:13.223:INFO [launcher]: Starting browser PhantomJS
23 12 2015 12:37:14.328:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket P1uadOEcO540gFfHAAAA with id 80626565
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 1 of 1 SUCCESS (0.002 secs / 0 secs)
```

(Funnily, it reports my OS X version wrong. I don't even know if that is Karma's or PhantomJS' doing.)

As you can see, I only get to see the output from the console. I'd like to know more about what is actually happening - like, having a real spec reporter.

How can I get that working?

**Comment by thelgevold** [comment]
One way to influence the output is through the reporter setting in karma.conf.js

Perhaps one of the options here is better suited: http://karma-runner.github.io/0.8/config/configuration-file.html

**Comment by IngwiePhoenix** [comment]
Ohh, okay. Thanks! I will look into that.

Thanks for making this lil’ repo. Got me set up in about two minutes. I even can use my actual webpack config since I can just require it. So, Now i can go and test away. :)

**Comment by mandysimon88** [comment]
I just installed this repo into an empty direct, ran `npm install` and then 'npm run tests'. I got the following errors. It'd be great if you could modify the repo so that it runs on clone... I know I need to add a webpack config to make it work, but having a working example would be really helpful.
```
WARN [preprocess]: Can not load "webpack"!
  TypeError: this.emitter.refreshFiles is not a function
    at Plugin.notifyKarmaAboutChanges (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/karma-webpack/lib/karma-webpack.js:143:16)
    at Plugin.<anonymous> (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/karma-webpack/lib/karma-webpack.js:98:12)
    at Compiler.applyPlugins (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:272:8)
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket hHxDv7sANdjKI1F81j5B with id 48786082
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/test-context.js:1
```
