### ISSUE TITLE
Cloned project does not work

### ISSUE THREAD

**Issue by amandapouget** [thelgevold/javascript-es6-unit-tests#3]
I just installed this repo into an empty directory, ran `npm install` and then `npm run tests`. I got the following errors. It'd be great if you could modify the repo so that it runs on clone... I know I need to add a webpack config to make it work, but having a working example would be really helpful.

```
WARN [preprocess]: Can not load "webpack"!
  TypeError: this.emitter.refreshFiles is not a function
    at Plugin.notifyKarmaAboutChanges (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/karma-webpack/lib/karma-webpack.js:143:16)
    at Plugin.<anonymous> (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/karma-webpack/lib/karma-webpack.js:98:12)
    at Compiler.applyPlugins (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/node_modules/webpack/lib/Compiler.js:272:8)
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket hHxDv7sANdjKI1F81j5B with id 48786082
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/amandasimon/Desktop/RoleModel/javascript-es6-unit-tests/test-context.js:1
```

**Comment by thelgevold** [comment]
Hi.
I upgraded two of the packages, so it should work now
